export const FETCH_PRODUCTS_SUCCESS = "FETCH PRODUCTS SUCCESS";
export const FETCH_PRODUCTS_REQUEST = "FETCH PRODUCTS REQUEST";
export const FETCH_PRODUCTS_FAILURE = "FETCH PRODUCTS FAILURE";
export const SEARCH_PRODUCT = "SEARCH PRODUCT";
